import {
  Heart, Users, Brain, Home, Smile, ShieldAlert, Activity, Clock, Car, Baby
} from "lucide-react";

import {
  ShowerHead,
  Shirt,
  Toilet,
  Accessibility,
  Sparkles,
  UtensilsCrossed,
  MessageCircle,
  Gamepad2,
  Lightbulb,
  MapPin,
  HeartHandshake,
  ShieldCheck,
  Eye,
  AlertTriangle,
  ChefHat,
  Droplets,
  CookingPot,
  WashingMachine,
  ShoppingCart,
  CalendarCheck,
  MoonStar,
  PhoneCall,
  RefreshCw,
  Globe,
  ClipboardList,
  TrendingUp,
  Stethoscope,
  Bell,
  ScanLine,
  UserCheck,
  HeartPulse,
  Building2,
  Layers,
} from "lucide-react";

export type PatientGroup = "seniors" | "adults" | "children";

export const services = [
  {
    id: 0,
    slug: "personal-care",
    title: "Personal Care & Daily Living Assistance",
    shortTitle: "Personal Care",
    tagline: "Dignity and independence, every single day.",
    description: "Our personal care services provide compassionate, respectful support with the activities that make daily life possible. We meet each client where they are — physically, emotionally, and medically — to design an approach that preserves their self-worth while ensuring safety.",
    icon: Heart,
    image: "https://images.unsplash.com/photo-1576765608866-5b51f8d8c2ab?auto=format&fit=crop&w=1200&q=80",
    accent: "#e53e8c",
    accentLight: "#fdf0f7",
    category: "Core Care",
    duration: "Hourly / Daily / 24/7",
    coverage: "Home, Assisted Living & Community",
    patientGroups: ["seniors", "adults"] as PatientGroup[],
    categorizedFeatures: [
      { title: "Personal Hygiene & Grooming", icon: ShowerHead, items: ["Bathing and showering assistance", "Sponge baths", "Oral hygiene and denture care", "Hair care and grooming", "Shaving assistance", "Skin care assistance", "Routine nail care assistance"] },
      { title: "Dressing & Appearance Support", icon: Shirt, items: ["Dressing and undressing", "Clothing selection assistance", "Assistance with shoes and outerwear", "Personal grooming support"] },
      { title: "Toileting & Continence Care", icon: Toilet, items: ["Toileting assistance", "Incontinence care", "Changing briefs and protective garments", "Perineal care", "Bathroom safety assistance"] },
      { title: "Mobility & Transfer Support", icon: Accessibility, items: ["Ambulation assistance", "Walking support", "Bed-to-chair transfers", "Chair-to-wheelchair transfers", "Positioning and repositioning", "Stair navigation assistance"] },
      { title: "Independence & Wellness Support", icon: Sparkles, items: ["Daily routine assistance", "Encouragement of self-care activities", "Monitoring of functional abilities", "Assistance maintaining independence"] },
      { title: "Eating & Hydration Assistance", icon: UtensilsCrossed, items: ["Meal setup", "Feeding assistance", "Hydration encouragement", "Assistance with adaptive eating devices"] },
    ],
    whoFor: ["Seniors aging in place who need hands-on daily living support", "Individuals recovering from major illness, stroke, or orthopedic surgery", "Adults living with progressive physical disabilities or chronic conditions", "Individuals at high risk of falls who require continuous standby assistance", "Those who just need an extra pair of hands during peak morning or evening hours"],
    howItWorks: [
      { step: "01", title: "Free Registered Nurse Consultation", desc: "Our care team assesses physical needs, home safety layout, and personal preferences during a comprehensive, no-obligation home visit." },
      { step: "02", title: "Customized Care Plan & Caregiver Match", desc: "We develop a tailored care plan and pair you with a certified caregiver suited to your personality, routine, and required care level." },
      { step: "03", title: "Care Begins with Supervised Introduction", desc: "Your dedicated caregiver arrives on your preferred schedule, often accompanied by a supervisor to ensure a smooth, comfortable transition." },
      { step: "04", title: "Ongoing Clinical Review & Adjustments", desc: "We conduct regular quality checks and formal care plan reviews to adjust service hours or techniques as your medical or physical needs evolve." },
    ],
  },
  {
    id: 1,
    slug: "companion-care",
    title: "Companion & Social Engagement Care",
    shortTitle: "Companion Care",
    tagline: "Connection that transforms quality of life.",
    description: "Loneliness is a silent health crisis. Our companion care service pairs clients with warm, thoughtful caregivers who provide genuine conversation, activity participation, and emotional presence — reducing isolation while supporting mental wellness.",
    icon: Users,
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1200&q=80",
    accent: "#0d9488",
    accentLight: "#f0fdfb",
    category: "Wellness",
    duration: "Flexible hourly schedules",
    coverage: "Home, Senior Centers & Community",
    patientGroups: ["seniors", "adults"] as PatientGroup[],
    categorizedFeatures: [
      { title: "Companionship & Emotional Support", icon: MessageCircle, items: ["Friendly conversation", "Emotional reassurance", "Meaningful companionship", "Social interaction and engagement"] },
      { title: "Recreational & Leisure Activities", icon: Gamepad2, items: ["Games and puzzles", "Reading and storytelling", "Arts and crafts", "Music and hobbies", "Indoor and outdoor activities"] },
      { title: "Cognitive Engagement", icon: Lightbulb, items: ["Memory stimulation activities", "Orientation reminders", "Brain fitness exercises", "Structured daily routines"] },
      { title: "Community & Social Participation", icon: MapPin, items: ["Accompaniment on walks", "Religious services attendance", "Family gatherings", "Community events and activities"] },
      { title: "Emotional Wellness & Mental Health Support", icon: HeartHandshake, items: ["Reducing loneliness and isolation", "Encouraging social connections", "Promoting emotional well-being", "Providing supportive companionship during life transitions"] },
    ],
    whoFor: ["Seniors living alone who feel isolated or are at risk of depression", "Individuals whose families live out of town or have busy work schedules", "Those with early-stage memory concerns who benefit from mental stimulation", "Active seniors looking for an outgoing peer to share in hobbies and outings", "Anyone who would benefit from a consistent, joyful, and encouraging presence"],
    howItWorks: [
      { step: "01", title: "Interest & Personality Profile", desc: "We map out the client's life history, favorite hobbies, literacy interests, and personality traits to define an ideal companion archetype." },
      { step: "02", title: "Companion Pairing & Meet-and-Greet", desc: "A compatible companion caregiver with shared interests is introduced gently to ensure mutual chemistry before regular shifts begin." },
      { step: "03", title: "Scheduled Engagement Visits", desc: "Regularly scheduled visits take place on your preferred days, focusing on purposeful activities that stimulate joy and mental agility." },
      { step: "04", title: "Family Portal Updates & Continuity", desc: "Families receive digital logs and brief updates after each visit, keeping you connected to your loved one's emotional and mental state." },
    ],
  },
  {
    id: 2,
    slug: "memory-care",
    title: "Memory Care & Safety Monitoring",
    shortTitle: "Memory Care",
    tagline: "Specialized, compassionate support for cognitive change.",
    description: "Living with Alzheimer's, dementia, or other cognitive conditions requires a specialized, patient-centered approach. Our memory care specialists are trained in validation therapy, structured routines, and safety protocols that reduce distress and maximize quality of life.",
    icon: Brain,
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=1200&q=80",
    accent: "#7c3aed",
    accentLight: "#f5f0ff",
    category: "Specialized Care",
    duration: "Daily / Overnight / Live-In",
    coverage: "Home-Based Secure Environments",
    patientGroups: ["seniors"] as PatientGroup[],
    categorizedFeatures: [
      { title: "Alzheimer's & Dementia Support", icon: Brain, items: ["Memory cueing and reminders", "Routine reinforcement", "Orientation assistance", "Structured daily schedules", "Redirection and reassurance"] },
      { title: "Cognitive Wellness Support", icon: Lightbulb, items: ["Reminiscence activities", "Memory games and exercises", "Cognitive engagement activities", "Social interaction for cognitive stimulation"] },
      { title: "Fall Prevention Services", icon: ShieldCheck, items: ["Transfer supervision", "Mobility monitoring", "Ambulation assistance", "Assistive device support", "Fall-risk observation"] },
      { title: "Home Safety Monitoring", icon: Eye, items: ["Environmental safety observations", "Clutter and trip hazard monitoring", "Lighting and accessibility review", "Bathroom safety monitoring"] },
      { title: "Wellness Observation & Monitoring", icon: Activity, items: ["Observation of physical condition", "Observation of behavioral changes", "Observation of mobility changes", "Observation of nutritional and hydration status", "Reporting significant concerns to supervisors and family"] },
      { title: "Emergency Preparedness & Response Support", icon: AlertTriangle, items: ["Emergency contact verification", "Emergency planning assistance", "Emergency response coordination", "Wellness and safety checks"] },
    ],
    whoFor: ["Individuals diagnosed with Alzheimer's disease, Lewy Body, or Vascular Dementia", "Families experiencing caregiving exhaustion from handling progressive memory loss", "Those experiencing frequent confusion, wandering behaviors, or evening agitation", "Clients who need a consistent, calming presence to prevent home accidents or panic"],
    howItWorks: [
      { step: "01", title: "Comprehensive Cognitive Assessment", desc: "We collaborate with the family and primary doctors to map out the current dementia stage, triggers, and baseline cognitive functions." },
      { step: "02", title: "Custom Behavioral Care Plan", desc: "We design a customized, structured daily plan built around existing life habits, sleep patterns, and preferred historical routines." },
      { step: "03", title: "Dementia-Certified Specialist Match", desc: "We assign a caregiver uniquely certified in advanced dementia care, validation techniques, and cognitive safety practices." },
      { step: "04", title: "Family Coaching & Care Coordination", desc: "We provide regular coaching notes to family members, ensuring consistent communication strategies and unified care practices across the board." },
    ],
  },
  {
    id: 3,
    slug: "home-nutrition",
    title: "Household & Nutrition Support",
    shortTitle: "Home & Nutrition",
    tagline: "A clean home and nourishing meals — the foundation of wellbeing.",
    description: "A safe, organized home environment and proper nutrition are the cornerstones of good health. Our household support services handle the practical tasks of daily life so clients can focus on living rather than managing chores.",
    icon: Home,
    image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=80",
    accent: "#d97706",
    accentLight: "#fffbeb",
    category: "Home Support",
    duration: "Scheduled part-time / Daily visits",
    coverage: "Home Interior",
    patientGroups: ["seniors"] as PatientGroup[],
    categorizedFeatures: [
      { title: "Meal Planning & Preparation", icon: ChefHat, items: ["Meal planning", "Grocery list preparation", "Meal preparation", "Healthy snack preparation", "Special dietary accommodation support"] },
      { title: "Nutrition & Hydration Support", icon: Droplets, items: ["Feeding assistance", "Hydration reminders", "Nutrition encouragement", "Monitoring food intake"] },
      { title: "Kitchen Management", icon: CookingPot, items: ["Kitchen cleanup", "Food storage organization", "Food safety monitoring", "Expiration date checks"] },
      { title: "Light Housekeeping Services", icon: Sparkles, items: ["Dusting", "Vacuuming", "Sweeping and mopping", "Dishwashing", "General tidying of living spaces"] },
      { title: "Laundry & Linen Services", icon: WashingMachine, items: ["Laundry and folding clothes", "Changing bed linens", "Making beds", "Organizing clothing"] },
      { title: "Errands & Shopping Assistance", icon: ShoppingCart, items: ["Grocery shopping", "Pharmacy pickup", "Household supply shopping", "Mailing and personal errands"] },
    ],
    whoFor: ["Seniors who find heavy household cleaning tasks painful or physically unsafe", "Individuals with limited mobility, severe arthritis, or low daily energy levels", "Those managing chronic conditions requiring complex, strict dietary guidelines", "Busy families who want to guarantee a clean, sanitary living space for an aging relative"],
    howItWorks: [
      { step: "01", title: "Home Environment & Diet Assessment", desc: "We tour the home to catalog cleaning priorities, identify safety red flags, and review dietary rules or physician restrictions." },
      { step: "02", title: "Customized Menu & Chore Checklist", desc: "A personalized, rotating meal plan is created alongside a highly specific daily and weekly household task schedule." },
      { step: "03", title: "Seamless Regular Service Scheduling", desc: "Visits are cleanly booked around the client's favorite lifestyle hours, ensuring minimum disruption to their day." },
      { step: "04", title: "Meticulous Field Supervision", desc: "Field supervisors perform periodic, unannounced quality spot-checks to guarantee elite hospitality and food safety standards are met." },
    ],
  },
  {
    id: 4,
    slug: "respite-care",
    title: "Family Respite & Caregiver Support",
    shortTitle: "Respite Care",
    tagline: "Rest is not a luxury. It's a medical necessity.",
    description: "Family caregivers are the unsung backbone of home care — and they burn out. Our respite care service provides qualified relief caregivers so families can step away with confidence, knowing their loved one is in skilled, compassionate hands.",
    icon: Smile,
    image: "https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=1200&q=80",
    accent: "#e11d48",
    accentLight: "#fff0f3",
    category: "Family Support",
    duration: "Hourly up to multi-week blocks",
    coverage: "Home & Short-term Travel",
    patientGroups: ["seniors", "adults", "children"] as PatientGroup[],
    categorizedFeatures: [
      { title: "In-Home Respite Care", icon: Home, items: ["Short-term caregiver relief", "Scheduled respite visits", "Temporary family caregiver coverage", "Flexible respite scheduling"] },
      { title: "Overnight Respite Support", icon: MoonStar, items: ["Evening supervision", "Overnight monitoring", "Bedtime assistance", "Nighttime safety support"] },
      { title: "Caregiver Wellness Support", icon: HeartHandshake, items: ["Reducing caregiver burden", "Providing peace of mind", "Supporting caregiver work-life balance", "Temporary relief during emergencies"] },
      { title: "Family Communication & Updates", icon: PhoneCall, items: ["Care updates for family members", "Reporting observations and concerns", "Coordination with authorized family representatives", "Care continuity support"] },
      { title: "Recovery & Transitional Support", icon: RefreshCw, items: ["Temporary assistance during caregiver absence", "Support following hospitalization of a family caregiver", "Assistance during family travel or emergencies"] },
    ],
    whoFor: ["Family members operating as the 24/7 primary caregiver for a relative", "Caregivers showing clinical signs of physical exhaustion, chronic stress, or illness", "Families preparing for an upcoming vacation, wedding, or major career change", "Anyone needing a trustworthy, fully vetted backup care safety net on short notice"],
    howItWorks: [
      { step: "01", title: "Meticulous Primary Caregiver Interview", desc: "We extract all the nuanced details of your loved one's care — routines, specific quirks, favorite phrases, and hidden medical triggers." },
      { step: "02", title: "Introductory Trial Visit", desc: "We coordinate a brief, fully paid introductory visit so the client can bond with the relief caregiver while you are still present." },
      { step: "03", title: "Seamless Relief Management", desc: "Your matched relief caregiver steps in and executes the established daily medical and domestic care plan with precision." },
      { step: "04", title: "Return Transition Debriefing", desc: "We conduct a detailed clinical and functional debrief when you return, highlighting updates on behavioral patterns or physical shifts." },
    ],
  },
  {
    id: 5,
    slug: "disability-support",
    title: "Disability Support Services",
    shortTitle: "Disability Support",
    tagline: "Maximizing capability, comfort, and independence.",
    description: "Every person living with a disability deserves care that focuses on what they can do, not what they cannot. Our disability support plans are built around individual goals, adaptive strategies, and a genuine commitment to autonomy and quality of life.",
    icon: ShieldAlert,
    image: "https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=1200&q=80",
    accent: "#4f46e5",
    accentLight: "#eef2ff",
    category: "Specialized Care",
    duration: "Flexible scheduled shifts",
    coverage: "Home, Workplace & Community Integration",
    patientGroups: ["adults"] as PatientGroup[],
    categorizedFeatures: [
      { title: "Physical Disability Support", icon: Accessibility, items: ["Mobility assistance", "Transfer assistance", "Personal care support", "Daily activity assistance", "Adaptive equipment support"] },
      { title: "Developmental Disability Support", icon: Layers, items: ["Structured daily routines", "Personal assistance services", "Community participation support", "Life skills reinforcement", "Independence-building activities"] },
      { title: "Cognitive & Behavioral Support", icon: Brain, items: ["Routine reinforcement", "Orientation assistance", "Redirection and reassurance", "Behavioral observation", "Cognitive engagement activities"] },
      { title: "Community Integration Services", icon: Globe, items: ["Community participation support", "Recreational activity assistance", "Social engagement opportunities", "Volunteer and community involvement support"] },
      { title: "Independent Living Services", icon: Home, items: ["Assistance with household tasks", "Personal organization support", "Appointment coordination", "Daily living skill development"] },
      { title: "Wellness & Safety Monitoring", icon: ShieldCheck, items: ["Observation of health status", "Monitoring functional abilities", "Safety supervision", "Reporting significant changes in condition"] },
    ],
    whoFor: ["Adults and young adults managing severe physical or neurological disabilities", "Individuals navigating developmental, learning, or complex intellectual disabilities", "People actively transitioning from clinical facilities to autonomous community living", "Families seeking structured, highly goal-oriented physical or cognitive support workers"],
    howItWorks: [
      { step: "01", title: "Collaborative Goal-Setting Session", desc: "The client, family, and case manager meet to establish specific independence milestones (e.g., vocational goals, motor skill training)." },
      { step: "02", title: "Adaptive Support Framework Design", desc: "We map out a structured strategy prioritizing client autonomy, communication preferences, and physical safety loops." },
      { step: "03", title: "Specialized Support Worker Match", desc: "We carefully pair the client with a support professional trained in specific physical transfers, neurodivergent care, or communication tech." },
      { step: "04", title: "Data-Driven Progress Milestone Tracking", desc: "We run monthly evaluations to review skill acquisition, physical adjustments, and modify target goals alongside therapy teams." },
    ],
  },
  {
    id: 6,
    slug: "recovery-care",
    title: "Recovery & Post-Hospital Support",
    shortTitle: "Recovery Care",
    tagline: "A safe bridge from hospital to home.",
    description: "The transition from hospital to home is one of the highest-risk periods for older adults. Our recovery care service ensures proper adherence to discharge instructions, monitors for complications, and provides the physical and emotional support needed to heal fully.",
    icon: Activity,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80",
    accent: "#059669",
    accentLight: "#f0fdf4",
    category: "Clinical Support",
    duration: "Short-term targeted (weeks to months)",
    coverage: "Home-Based Transition",
    patientGroups: ["seniors", "adults", "children"] as PatientGroup[],
    categorizedFeatures: [
      { title: "Hospital-to-Home Transition Services", icon: RefreshCw, items: ["Support following hospital discharge", "Assistance after rehabilitation stays", "Recovery support after illness", "Recovery support following surgery"] },
      { title: "Daily Living Recovery Assistance", icon: ClipboardList, items: ["Personal care assistance", "Mobility support", "Meal preparation", "Household support"] },
      { title: "Wellness Observation & Monitoring", icon: Eye, items: ["Observation for changes in condition", "Monitoring mobility and strength", "Observation of recovery progress", "Reporting concerns to authorized parties"] },
      { title: "Follow-Up Care Coordination", icon: CalendarCheck, items: ["Appointment reminders", "Transportation to follow-up visits", "Coordination with family caregivers", "Recovery support planning"] },
      { title: "Short-Term Recovery Support", icon: TrendingUp, items: ["Temporary care assistance", "Transitional support services", "Reinforcement of discharge instructions (non-clinical)", "Recovery-focused companionship"] },
    ],
    whoFor: ["Individuals recovering from orthopedic surgery, cardiac events, or complex illnesses", "Seniors carrying a statistically high clinical risk of hospital readmission", "Those who live alone and lack an immediate family safety net for overnight post-op care", "Patients managing new, complex post-discharge medical devices or routines"],
    howItWorks: [
      { step: "01", title: "Pre-Discharge Hospital Liaison", desc: "Our nursing lead coordinates directly with your hospital discharge team before you leave to capture surgical history and prescriptions." },
      { step: "02", title: "Post-Op Home Setup & Sanitization", desc: "We prepare the home layout, install temporary grab bars, configure recovery equipment, and clear fall hazards." },
      { step: "03", title: "Intensive Post-Acute Transition Support", desc: "Care starts with dedicated daily shifts during the critical 72-hour window when readmission metrics are highest." },
      { step: "04", title: "Gradual Step-Down Plan", desc: "We scale down service frequency over several weeks as physical independence, stamina, and wound recovery benchmarks are met." },
    ],
  },
  {
    id: 7,
    slug: "medication-wellness",
    title: "Medication Reminders & Wellness Checks",
    shortTitle: "Medication & Wellness",
    tagline: "Consistent wellness management, day after day.",
    description: "Medication non-adherence is one of the leading causes of preventable hospitalizations. Our wellness service keeps clients on track with timely medication reminders, health monitoring, and routine wellness checks that catch problems before they escalate.",
    icon: Clock,
    image: "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=1200&q=80",
    accent: "#ea580c",
    accentLight: "#fff7ed",
    category: "Wellness",
    duration: "Daily check-ins / Drop-in shifts",
    coverage: "In-Home Vitals Tracking & Remote Safety Logs",
    patientGroups: ["seniors", "adults", "children"] as PatientGroup[],
    categorizedFeatures: [
      { title: "Medication Reminder Services", icon: Bell, items: ["Verbal medication reminders", "Medication schedule prompts", "Reminder documentation", "Observation of self-administration"] },
      { title: "Medication Compliance Monitoring", icon: ScanLine, items: ["Reporting missed doses", "Reporting medication refusals", "Reporting medication-related concerns", "Family notification as authorized"] },
      { title: "Wellness Checks", icon: HeartPulse, items: ["Routine wellness observations", "Monitoring changes in condition", "Observation of appetite and hydration", "Observation of mobility and function"] },
      { title: "Safety Monitoring", icon: ShieldCheck, items: ["Observation for falls or safety concerns", "Monitoring environmental safety", "Wellness and reassurance visits", "Escalation of urgent concerns"] },
      { title: "Health & Wellness Support", icon: Activity, items: ["Healthy habit encouragement", "Hydration reminders", "Nutrition encouragement", "Wellness education reinforcement"] },
    ],
    whoFor: ["Seniors managing polypharmacy regimens (taking 5+ distinct medications daily)", "Individuals dealing with chronic conditions like type-2 diabetes, hypertension, or heart failure", "Those experiencing early memory changes who occasionally lose track of dosage timings", "Anxious families who want a reliable, daily professional validation of their relative's vitals"],
    howItWorks: [
      { step: "01", title: "Clinical Pharmacy & Medication Mapping", desc: "We catalog every single drug, supplement, dosage timeline, food restriction, and potential cross-interaction side effect." },
      { step: "02", title: "Customized Vitals Monitoring Schedule", desc: "We set up a tracking chart capturing exactly when and how blood pressure, glucose, or weight parameters must be recorded." },
      { step: "03", title: "Daily Wellness Checks Execution", desc: "A professional checks in at specified hours to confirm medication consumption and track essential biometric data points." },
      { step: "04", title: "Unified Weekly Health Reports", desc: "A consolidated digital trend chart is sent weekly to your family and chosen physicians to spot negative patterns early." },
    ],
  },
  {
    id: 8,
    slug: "transportation",
    title: "Transportation & Appointment Assistance",
    shortTitle: "Transportation",
    tagline: "Never miss an appointment that matters.",
    description: "Lack of transportation is a major barrier to healthcare access for older adults. Our transportation service provides safe, punctual, accompanied transport to appointments, therapies, pharmacies, and social events — ensuring clients stay connected to their healthcare and community.",
    icon: Car,
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80",
    accent: "#0284c7",
    accentLight: "#f0f9ff",
    category: "Community Access",
    duration: "Per-trip booking / Recurring travel blocks",
    coverage: "Regional Door-to-Door Outings",
    patientGroups: ["adults", "children"] as PatientGroup[],
    categorizedFeatures: [
      { title: "Medical Transportation", icon: Stethoscope, items: ["Physician appointments", "Specialist appointments", "Therapy visits", "Diagnostic testing appointments", "Outpatient procedure transportation"] },
      { title: "Healthcare Escort Services", icon: UserCheck, items: ["Accompaniment to appointments", "Assistance with check-in and registration", "Mobility assistance during appointments", "Return-home assistance"] },
      { title: "Personal Transportation", icon: ShoppingCart, items: ["Grocery shopping", "Pharmacy visits", "Banking errands", "Personal errands and appointments"] },
      { title: "Employment & Education Transportation", icon: Building2, items: ["Transportation to work", "Transportation to vocational programs", "Transportation to educational activities", "Transportation to job interviews"] },
      { title: "Community Participation Transportation", icon: MapPin, items: ["Religious services", "Community programs", "Social events", "Recreational activities"] },
      { title: "Transportation Safety Support", icon: ShieldCheck, items: ["Door-to-door assistance", "Vehicle entry and exit assistance", "Wheelchair and mobility support", "Travel safety supervision"] },
    ],
    whoFor: ["Seniors who have chosen to stop driving or live with vision impairments", "Individuals dealing with severe mobility limitations or neurological conditions", "Those who have frequent specialized clinical appointments throughout the week", "Anyone who values a physical, encouraging chaperone rather than riding alone in a taxi or rideshare"],
    howItWorks: [
      { step: "01", title: "Calendar Sync & Scheduling", desc: "We map out your upcoming outpatient schedules, medical checkups, and errands onto a unified master logistics calendar." },
      { step: "02", title: "Mobility & Vehicle Matching", desc: "We select the appropriate vehicle and caregiver support based on your physical equipment needs (e.g., folding walkers, extra legroom)." },
      { step: "03", title: "Escorted Door-to-Door Transportation", desc: "Our caregiver assists you out of the house, drives safely, chaperones you right into the clinic, and stays by your side." },
      { step: "04", title: "Outing Completion & Family Notification", desc: "We return you safely to your home, set up your purchases or prescriptions, and send a completion message to your family." },
    ],
  },
  {
    id: 9,
    slug: "pediatric-care",
    title: "Pediatric & Child Care Services",
    shortTitle: "Pediatric Care",
    tagline: "Nurturing the next generation with expert, attentive care.",
    description: "Our pediatric care service delivers specialized, loving support for infants, toddlers, and children with unique developmental or medical needs. Every caregiver is trained in pediatric first aid and child development to provide truly expert care.",
    icon: Baby,
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1200&q=80",
    accent: "#7c3aed",
    accentLight: "#faf5ff",
    category: "Pediatric",
    duration: "Flexible hourly / Overnight adjustments",
    coverage: "Home, School & Pediatric Facility Companion",
    patientGroups: ["children"] as PatientGroup[],
    categorizedFeatures: [
      { title: "Personal Hygiene & Grooming", icon: ShowerHead, items: ["Bathing assistance", "Oral hygiene assistance", "Hair care and grooming", "Dressing and undressing assistance", "Toileting assistance", "Diapering assistance", "Continence care assistance"] },
      { title: "Mobility & Daily Living Support", icon: Accessibility, items: ["Ambulation assistance", "Transfer assistance", "Positioning and repositioning", "Assistance with mobility devices", "Daily routine assistance"] },
      { title: "Feeding Assistance", icon: UtensilsCrossed, items: ["Meal setup", "Feeding assistance", "Hydration assistance", "Assistance during mealtimes"] },
      { title: "Companionship & Supervision Services", icon: Users, items: ["Social interaction and companionship", "Recreational activities", "Reading and storytelling", "Games and age-appropriate activities", "Emotional support and encouragement", "General supervision", "Monitoring safety within the home", "Structured daily routine support", "Observation of well-being"] },
      { title: "Special Needs & Routine Support", icon: ClipboardList, items: ["Assistance with activities of daily living", "Assistance following established routines", "Reinforcement of daily schedules", "Support with age-appropriate independence", "Supervision during daily activities"] },
      { title: "Safety & Wellness Monitoring", icon: ShieldCheck, items: ["Observation of well-being", "Safety supervision", "Monitoring for changes in condition", "Reporting concerns to parents or guardians", "Emergency contact verification", "Emergency response assistance"] },
      { title: "School & Community Transportation", icon: Car, items: ["Transportation to and from school", "Transportation to educational programs", "Transportation to school-sponsored activities", "Transportation to physician appointments", "Transportation to therapy appointments", "Transportation to recreational activities", "Transportation to religious services", "Door-to-door assistance and safety supervision"] },
      { title: "Meal Preparation & Nutrition", icon: ChefHat, items: ["Preparation of meals and snacks", "Meal planning assistance", "Food preparation according to family instructions", "Kitchen cleanup following meal preparation", "Feeding support and hydration encouragement", "Following prescribed dietary preferences", "Encouraging healthy eating habits", "Monitoring meal consumption"] },
      { title: "Medication Reminders", icon: Bell, items: ["Verbal medication reminders", "Scheduled medication prompts", "Observation of self-administration when appropriate", "Documentation of reminders provided", "Reporting missed doses to parents or guardians"] },
      { title: "Respite Care for Parents", icon: HeartHandshake, items: ["Temporary caregiver relief", "Short-term supervision", "Scheduled respite visits", "Flexible respite scheduling", "Evening supervision and overnight monitoring", "Bedtime assistance and nighttime safety observation", "Temporary care during family emergencies"] },
      { title: "Post-Hospital Recovery Support", icon: Activity, items: ["Personal care assistance during recovery", "Feeding and mobility assistance", "Supervision during recovery", "Observation for changes in condition", "Transportation to follow-up appointments", "Assistance with daily routines during recovery"] },
    ],
    whoFor: ["Families managing newborns or medically complex infants requiring close care", "Parents raising children diagnosed with neurodivergent conditions, autism, or delays", "Demanding professional households seeking elite, safety-certified in-home childcare professionals", "Families navigating a child's short-term post-surgical recovery or rehabilitation plan"],
    howItWorks: [
      { step: "01", title: "Family Routine & Medical Consultation", desc: "We sit down with parents and clinical histories to review your child's emotional triggers, therapeutic goals, and favorite home routines." },
      { step: "02", title: "Pediatric Specialist Vetting & Matching", desc: "We pair your family with a certified professional possessing background experience in early childhood education or pediatric nursing fields." },
      { step: "03", title: "Supervised Introductory Play Session", desc: "A carefully managed intro session builds safety, bounds, and emotional comfort for your child before individual care kicks off." },
      { step: "04", title: "Granular Daily Progress Tracking", desc: "Parents receive detailed daily logs mapping out nutritional values, mood metrics, educational wins, and biometric readings." },
    ],
  },
];